[package]
name = "evil"
description = "Visualise collider events"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"
keywords = ["physics"]
categories = ["science"]
repository = "https://github.com/a-maier/evil"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
bzip2 = "0.4.3"
env_logger = "0.9.0"
flate2 = "1.0.20"
hepmc2 = "0.4.1"
lazy_static = "1.4.0"
lhef = "0.3.4"
log = "0.4.14"
lz4 = "1.23.2"
plotters = "0.3.1"
plotters-backend = "0.3.1"
structopt = "0.3.22"
zstd = "0.9.0"
